# Generated by Django 5.1.3 on 2024-11-13 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='level',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Уровень группы должен быть не менее 1'), django.core.validators.MaxValueValidator(4, message='Уровень группы должен быть не более 4')], verbose_name='Уровень группы'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Название группы должно быть в формате SEP-XXX.X', regex='^SEP-\\d{3}\\.\\d$')], verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='student',
            name='avg_mark',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0, message='Средний балл должен быть не менее 0'), django.core.validators.MaxValueValidator(10, message='Средний балл должен быть не более 10')], verbose_name='Средний балл'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(1900, message='Год рождения должен быть не ранее 1900')], verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Имя должно начинаться с заглавной буквы и содержать только буквы', regex='^[A-Z][a-z]+$')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Фамилия должна начинаться с заглавной буквы и содержать только буквы', regex='^[A-Z][a-z]+$')], verbose_name='Фамилия'),
        ),
    ]
